### ISSUE TITLE
five-or-more candidate missing graphics

### ISSUE THREAD

**Issue by jbicha** [ubuntu/five-or-more#8]
five-or-more from the candidate channel (189) doesn't work. It doesn't display the game pieces on the board. The stable channel (186) works.

```
$ snap run five-or-more

** (five-or-more): WARNING **: theme-renderer.vala:78: Unable to load default theme
** (five-or-more): WARNING **: theme-renderer.vala:81: Unable to load chosen theme
(five-or-more): librsvg-CRITICAL **: rsvg_handle_render_cairo: assertion 'is_rsvg_handle(handle)' failed
```

**Comment by hellsworth** [comment]
I agree the images are missing.. I have no idea why though. The theme-renderer is just not being used and I wonder if it's because of the change from public to private classes found in https://gitlab.gnome.org/GNOME/five-or-more/-/commit/361fd9720c4437ac7786012d6872dc2f746def53

@kenvandine do you have any suggestions?
